apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: playlist-angular-frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: musicstore
    app.kubernetes.io/name: playlist-angular-frontend
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"    
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: gitops_commit_message
      value: playlist-angular-frontend dev supplychain@cluster.local
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
